// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using Shop.Data;
using System;

namespace Shop.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20190501204729_AddShoppingCartItem")]
    partial class AddShoppingCartItem
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Shop.Data.Models.Category", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd();

                b.Property<string>("Description");

                b.Property<string>("ImageUrl");

                b.Property<string>("Name");

                b.HasKey("Id");

                b.ToTable("Categories");
            });

            modelBuilder.Entity("Shop.Data.Models.GraphicPhoto", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd();

                b.Property<int>("CategoryId");

                b.Property<string>("ImageUrl");

                b.Property<bool>("InStock");

                b.Property<bool>("IsPreferedGraphicPhoto");

                b.Property<string>("LongDescription");

                b.Property<string>("Name");

                b.Property<decimal>("Price");

                b.Property<string>("ShortDescription");

                b.HasKey("Id");

                b.HasIndex("CategoryId");

                b.ToTable("GraphicPhotos");
            });

            modelBuilder.Entity("Shop.Data.Models.ShoppingCartItem", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd();

                b.Property<int>("Amount");

                b.Property<int?>("GraphicPhotoId");

                b.Property<string>("ShoppingCartId");

                b.HasKey("Id");

                b.HasIndex("GraphicPhotoId");

                b.ToTable("ShoppingCartItems");
            });

            modelBuilder.Entity("Shop.Data.Models.GraphicPhoto", b =>
            {
                b.HasOne("Shop.Data.Models.Category", "Category")
                    .WithMany("GraphicPhotos")
                    .HasForeignKey("CategoryId")
                    .OnDelete(DeleteBehavior.Cascade);
            });

            modelBuilder.Entity("Shop.Data.Models.ShoppingCartItem", b =>
            {
                b.HasOne("Shop.Data.Models.GraphicPhoto", "GraphicPhoto")
                    .WithMany()
                    .HasForeignKey("GraphicPhotoId");
            });
#pragma warning restore 612, 618
        }
    }
}